FROM python:3.9.13

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# Install production dependencies.
RUN python -m pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir dask-cloudprovider[aws]

ENV APP_HOME /hwpc-calculator
WORKDIR $APP_HOME
COPY ./src/ ./src/
COPY ./data ./data

COPY ./dist/hwpccalc-0.0.1-py3-none-any.whl ./hwpccalc-0.0.1-py3-none-any.whl
RUN pip install --no-cache-dir ./hwpccalc-0.0.1-py3-none-any.whl

COPY .env .env
# COPY README.md README.md
# COPY setup.py setup.py

EXPOSE 8786
EXPOSE 8787

CMD ["python", "src/hwpccalc/hwpccalc.py"]